name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install @octokit/rest
      
      - name: Run script
        run: node issue_project_generator.js
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          MY_USERNAME: ${{ secrets.MY_USERNAME }}
