name: Create Repositories

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  create-repos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!
        
