name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          git config user.name ${{ secrets.MY_NAME }}
          git config user.email ${{ secrets.MY_EMAIL }}
          git add .
          git commit -m "generated"
          git push
          
#       - uses: actions/checkout@v3
#       - name: Checkout Repository
#       - uses: actions/checkout@v3
#       - name: set up JDK 11
#         uses: actions/setup-java@v3
#         with:
#           java-version: '11'
#           distribution: 'temurin'
#           cache: gradle
