name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Install dependencies
        run: npm install @octokit/rest
      - name: Run script
