name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install @octokit/rest
      
      - name: Run script
        run: node my-script.js
        env:
          MY_NAME: ${{ secrets.MY_NAME }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_USERNAME: ${{ secrets.MY_USERNAME }}
